#!/bin/bash -e

cd "$(dirname "$0")/.."

docker run --rm \
  --volume "$(pwd):/app" \
  --workdir "/app/deployment" \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_DEFAULT_REGION=ap-southeast-1 \
  hashicorp/terraform:0.14.4 \
  "${@}"